function Set-NBBJ365Permission{
param(
[parameter(Mandatory=$True)][string]$User,
[parameter(Mandatory=$True)][ValidateSet("US","UK","CN")][string]$CountryCode
)
$LicenseOptions = New-MsolLicenseOptions -AccountSkuId nbbj4:ENTERPRISEPREMIUM -DisabledPlans INFORMATION_BARRIERS,KAIZALA_STANDALONE,PREMIUM_ENCRYPTION,WHITEBOARD_PLAN3,MIP_S_CLP2,MIP_S_CLP1,MYANALYTICS_P2,PAM_ENTERPRISE,BPOS_S_TODO_3,FORMS_PLAN_E5,STREAM_O365_E5,THREAT_INTELLIGENCE,FLOW_O365_P3,ADALLOM_S_O365,EQUIVIO_ANALYTICS,LOCKBOX_ENTERPRISE,EXCHANGE_ANALYTICS,SWAY,ATP_ENTERPRISE,MCOEV,MCOMEETADV,MICROSOFT_SEARCH,POWERAPPS_O365_P3,MCOEV,EXCHANGE_S_ENTERPRISE,MCOSTANDARD,YAMMER_ENTERPRISE,RMS_S_ENTERPRISE,PROJECTWORKMANAGEMENT,Deskless

Set-MsolUser -UserPrincipalName $User -UsageLocation $CountryCode
Set-MsolUserLicense -UserPrincipalName $User -AddLicenses "nbbj4:ENTERPRISEPREMIUM" -LicenseOptions $LicenseOptions

}